/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import oshi.SystemInfo;
import oshi.hardware.Disks;
import oshi.hardware.HWDiskStore;
import oshi.hardware.HWPartition;
import oshi.util.FormatUtil;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public int getSum(int a, int b){return a+b;}

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        var sys = new SystemInfo();
        var hardware = sys.getHardware();
        var cpu = hardware.getProcessor();
        var mem = hardware.getMemory();



        var memUsed = mem.getTotal() - mem.getAvailable();

        while (true) {
            try {
                System.out.println("CPU:           " + cpu.getSystemCpuLoad());
                System.out.println("Memoria Total: "+ mem.getTotal());
                System.out.println("Memoria Free:  "+ mem.getAvailable());
                System.out.println("Memoria Usada: "+ memUsed);
                Thread.sleep(1000);
            } catch (Exception e){
            }
        }









    }
}
