/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void testSum(){
    	App a = new App();
    	assertEquals("should sum", a.getSum(1, 2), 3);
    	assertEquals("should sum", a.getSum(0, 0), 0);
    	assertEquals("should sum", a.getSum(-1, 1), 0);
    	assertEquals("should sum", a.getSum(-1, 2), 10);
    }
}
