from core.ajax.sign_in import *
from core.ajax.sign_up import *
from core.ajax.setup_discord_dm import *
from core.ajax.query_last_data import *
from core.ajax.query_last_alerts import *
from core.ajax.ping import *
from core.ajax.agent_config import *
from core.ajax.remove_discord import *
from core.ajax.update_user import *
